### ISSUE TITLE
chef > bento

### ISSUE THREAD

**Issue by callelidstrom** [itds-consulting/tetra-listener-vagrant#1]
Chef can't be found. Replace with bento. 

foo:tetra-listener-vagrant user$ vagrant up --provider virtualbox
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'chef/ubuntu-14.04' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'chef/ubuntu-14.04'
    default: URL: https://atlas.hashicorp.com/chef/ubuntu-14.04
The box you're adding has a name different from the name you
requested. For boxes with metadata, you cannot override the name.
If you're adding a box using `vagrant box add`, don't specify
the `--name` parameter. If the box is being added via a Vagrantfile,
change the `config.vm.box` value to match the name below.

Requested name: chef/ubuntu-14.04
Actual name: bento/ubuntu-14.04

**Comment by smarek** [comment]
Looks like chef/ubuntu-14.04 was cached in my env, i've updated to bento/ubuntu-14.04 and fixed bugs that came along
