### ISSUE TITLE
amr code doesn't compile

### ISSUE THREAD

**Issue by callelidstrom** [itds-consulting/tetra-listener-vagrant#2]
==> default: patching file amr-code/makefile
==> default: patching file c-code/makefile
==> default: patching file amr-code/makefile
==> default: patching file c-code/makefile
==> default: patching file amr-code/channel.h
==> default: patching file amr-code/source.h
==> default: patching file amr-code/tetra_op.c
==> default: patching file c-code/channel.h
==> default: patching file c-code/source.h
==> default: patching file c-code/sub_dsp.c
==> default: patching file c-code/sub_sc_d.c
==> default: patching file c-code/tetra_op.c
==> default: patching file amr-code/init_params.c
==> default: patching file c-code/makefile
==> default: patching file amr-code/makefile
==> default: make: Entering directory `/root/tetra-listener/codec/amr-code'
==> default: gcc ccoder.c   ccod_tet.c  init_params.c   sub_cc.c tetra_op.c -g -I. -Wall -m32 -O2 -o ccoder
==> default: /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.8/libgcc.a when searching for -lgcc
==> default: /usr/bin/ld: cannot find -lgcc
==> default: /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.8/libgcc_s.so when searching for -lgcc_s
==> default: /usr/bin/ld: cannot find -lgcc_s
==> default: collect2: error: ld returned 1 exit status
==> default: make: Leaving directory`/root/tetra-listener/codec/amr-code'
==> default: make: **\* [ccoder] Error 1

**Comment by smarek** [comment]
This is due to missing `automake` package, that was installed in chef/ubuntu-14.04, but not here. Fixed in latest commit

**Comment by smarek** [comment]
Sorry, mistake, fixed now in eae6f7dc4154a5dcd2c8c381b723795b2f135d35
